
blank_issues_enabled: false
contact_links:
  - name: 📄 Contributing Guidelines
    url: ../CONTRIBUTING.md
    about: Please review our contributing standards before opening a new issue.
  - name: 💬 Discussions
    url: https://github.com/<your-username>/instagate/discussions
    about: Use Discussions for brainstorming or questions.
